server {
    listen 80;
    server_name localhost;
    root C:/path/to/your/public;

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        
        # Forward requests directly to your Go application proxy
        # Do not change the port, currently it is not supported and always listens 9000
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}